name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Call my composite action
        uses: ./.github/actions/greet
        with:
          who: Hari
      - name: Build step
        run: echo "Building the project"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Testing after build finished"
